class Book {
  String title,
      writer,
      price,
      image,
      lmao,
      description =
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id neque libero. Donec finibus sem viverra, luctus nisi ac, semper enim. Vestibulum in mi feugiat, mattis erat suscipit, fermentum quam. Mauris non urna sed odio congue rhoncus. \nAliquam a dignissim ex. Suspendisse et sem porta, consequat dui et, placerat tortor. Sed elementum nunc a blandit euismod. Cras condimentum faucibus dolor. Etiam interdum egestas sagittis. Aliquam vitae molestie eros. Cras porta felis ac eros pellentesque, sed lobortis mi eleifend. Praesent ut.';
  int pages;
  double rating;

  Book(
      this.title, this.writer, this.price, this.image, this.rating, this.pages, this.lmao);
}

final List<Book> books = [
  Book('CorelDraw untuk Tingkat Pemula Sampai Mahir', 'Jubilee Enterprise',
      'Rp 50.000', 'assets/corel.jpg', 3.5, 123, 'Buku ini ditujukan untuk pengguna CorelDraw dari level pemula sampai mahir. Level pemula bisa mengenal CorelDraw dari nol sedangkan level mahir bisa belajar menggambar objek-objek dan sulit.\n Pembahasan di dalam buku ini mencakup: \n - Pengenalan interface CorelDraw \n - Bekerja dengan file desain CorelDraw \n - Menggambar menggunakan Line dan Outline \n - Pemberian warna pada objek \n - Gambar bitmap di dalam desain grafis \n - Efek-efek bitmap di dalam CorelDraw \n - Ekspor untuk desain website \n Keterampilan: Pemula, Menengah Kelompok: Grafik Jenis buku: Referensi, Tutorial'),
  Book('Buku Pintar Drafter Untuk Pemula Hingga Mahir', 'Widada', 'Rp 55.000',
      'assets/drafter.jpg', 4.5, 200, 'Buku ini berisi tutorial praktis menggunaka 4 software rancang bangun paling popular. Materi isinya akan mengajarkan anda desain rancang bangun secara step by step. Multi aplikasi yang digunakan adalah AutoCad, Google Sketchup, Archicad, dan 3ds max. Dengan keempat software tersebut dalam waktu singkat Anda sudah menguasai bagaimana menggambar objek 2d, mengelola objek 2d, mendesain denah rumah, mendesain rumah minimalis, mendesain rumah minimalis, mendesain rumah tinggal dan modeling rumah sederhana.'),
  Book('Adobe InDesign: Seri Panduan Terlengkap', 'Jubilee Enterprise',
      'Rp 60.000', 'assets/indesign.jpg', 5.0, 324, 'Buku ini membantu para layouter untuk memahami Adobe InDesign. Pembahasan dimulai dari pengenalan interface, bekerja dengan teks, pembuatan tabel, mengelola dokumen, pewarnaan, dan sebagainya. Diharapkan, pembaca bisa membuat layout secara mandiri. Fitur-fitur utama yang sering digunakan dibahas secara lengkap dan mendalam. Karena berjenis referensi, maka pembaca akan menemukan banyak pengetahuan di balik canggihnya fitur Adobe InDesign. Meskipun membahas Adobe InDesign CC 2019, tapi pengguna versi lawas juga dapat mengikuti bahasan di dalam buku ini.'),
  Book('Pemodelan Objek Dengan 3Ds Max 2014', 'Wahana Komputer', 'Rp 58.000',
      'assets/max_3d.jpeg', 3.0, 200, 'Model 3D merupakan pilihan terbaik untuk menampilkan objek dengan gambaran yang lebih realistis. Berbeda dengan metode konvensional seperti sketsa yang pandangannya terbatas pada 2 dimensi, desain 3D memungkinkan Anda melihat bentuk objek dari segala sisi. Lewat pemodelan 3D, Anda dapat menambahkan tekstur dan pencahayaan sehingga model yang dibuat tampak seperti objek asli. Dari penjelasan tersebut terlihat betapa pentingnya merepresentasikan objek yang realistis bagi yang menyaksikan atau calon pengguna. Melalui kemampuan 3ds Max 2014, proses pembuatan model 3D menjadi semakin mudah dan hemat. Buku Panduan Aplikatif dan Solusi (PAS): Pemodelan Objek dengan 3ds Max 2014 ini akan memandu Anda untuk membuat objek 3D. Referensi objek yang menjadi model berupa perabot rumah tangga, seperti sofa, tempat tidur, lemari, vas bunga, dan masih banyak lagi. Buku ini juga dilengkapi gambar dan petunjuk langkah demi langkah yang akan memudahkan Anda dalam memahami isi buku'),
  Book('Penerapan Visualisasi 3D Dengan Autodesk Maya', 'Dhani Ariatmanto',
      'Rp 90.000', 'assets/maya.jpeg', 4.8, 234, 'Penerapan Visualisasi 3D Dengan Autodesk Maya, Modelling- UV Mapping -Texturing+cd \n Penulis: DhaniAriatmanto Abisika Yoga Erlangga \nPenerbit: Andi Publisher \n ISBN: 978-979-29-5166-0 \n Tahun: 2015 \n Edisi: I \n Cetakan: 1st Published \n Format: 16x23 \n Jumlah Halaman: x+166'),
  Book('Teknik Lancar Menggunakan Adobe Photoshop', 'Jubilee Enterprise',
      'Rp 57.000', 'assets/photoshop.jpg', 4.5, 240, 'Kalau Anda ingin lancer menguasai Photoshop dari nol dan ingin menjadi desainergrafis, editor foto, atau penggemar digital imaging, maka bacalah buku ini.Pembahasan buku ini meliputi: \n - Mengenal tool Photoshop dari nol \n - Pengenalan efek khusus menggunakan filter \n - Berbagai metode seleksi foto \n - Menggunakan Channel untuk seleksi \n - Quick Mask untuk membuat layer maskDalam waktu singkat dijamin Anda bisa menggunakan Photoshop. \n Bisa pula menggambar dan mengedit foto menggunakan software ini.'),
  Book('Adobe Premiere Terlengkap dan Termudah', 'Jubilee Enterprise',
      'Rp 56.000', 'assets/premier.jpg', 4.8, 432, 'Video editor akhir-akhir ini menjadi hobi dan profesi yang menjanjikan. Selain karena faktor Youtube dan aplikasi smartphone, profesi video editor adalah pekerjaan yang memiliki umur sangat panjang. Oleh karena itu, mari mempelajari ilmu mengedit video sejak dini agar Anda bisa mendapatkan banyak keuntungan baik untuk jangka pendek maupun jangka panjang. Apakah untuk mengedit video harus memerlukan komputer kekinian? Tidak perlu. Anda bisa memanfaatkan Adobe Premiere Pro versi lama. Tetapi bagi Anda yang telah memiliki komputer canggih, Anda juga bisa menggunakan Adobe Premiere CC yang terbaru. Oleh karena itulah, buku ini menggabungkan dua versi yang terpaut jauh dalam satu buku agar bisa dinikmati oleh pengguna komputer versi lama maupun baru sekaligus. Tujuannya, agar para pembaca bisa sama-sama memakai Adobe Premiere! Ayo, belajar mengedit video menggunakan Adobe Premiere. Kalau Anda sudah berhasil membuat video yang menarik, maka Anda bisa mengubahnya menjadi video cd, dvd, atau mem-publish-nya ke Youtube!'),
  Book('Cad Series : Google Sketchup Untuk Desain 3D', 'Wahana Komputer',
      'Rp 55.000', 'assets/sketchup.jpeg', 4.5, 321, 'CAD Series: Google SketchUp ini merupakan buku ketiga dari seri CAD yang dikeluarkan Wahana computer. Buku ini ditulis secara rinci dan detail sehingga mudah dipahami oleh semua kalangan pembaca. \n Buku ini akan membahas: \n - Perintah Dasar Google SketchUp \n - Menggambar Pintu Tiga Dimensi \n - Menggambar Jendela Tiga Dimensi \n - Menggambar bentuk rumah Tiga Dimensi'),
  Book('Webmaster Series : Trik Cepat Menguasai CSS', 'Wahana Komputer',
      'Rp 54.000', 'assets/webmaster.jpeg', 3.5, 431, 'Seiring dengan perkembangan dunia internet, pemrograman aplikasi berbasis web pun semakin berkembang pesat. CSS sebagai salah satu bagian pemrograman web pun ikut terkena dampaknya. Hal ini ditandai dengan berbagai macam website dengan tampilan yang menarik. Sebuah website dibuat semenarik mungkin supaya pengunjung nyaman menjelajahi isi website yang Anda buat dan tertarik untuk kembali mengunjungi website di lain waktu. Di sinilah peran CSS supaya website yang Anda buat tampak menarik. Buku ini merupakan seri kedua dari rangkaian seri buku Webmaster Series. Jika pada buku pertama telah dijelaskan tentang dasar-dasar membangun website menggunakan bahasa HTML, maka di dalam buku kedua ini Anda akan diajarkan bagaimana mengelola tampilan website menggunakan CSS. Setiap langkah yang dijelaskan dalam buku ini dimulai dari dasar hingga ke contoh penerapannya sehingga dapat langsung Anda praktikkan. Buku ini akan membahas: Pengenalan CSS Tata Cara Penggunaan CSS Penerapan CSS '),
];
